ECIAPP/Controllers/SuperAdminController.cs
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ECIAPP.Models;
using System.Net;
using System.Net.Mail;
using ECIModel;
using ECIDataAccess;
using System.IO;
using System.Text;
using System.Drawing;
using System.Web.Script.Serialization;
using ECIBusinessLogic;
using Newtonsoft.Json;

namespace ECIAPP.Controllers
{
    //[SessionExpireFilterAttribute()]
    public class SuperAdminController : Controller
    {
        //
        // GET: /Home/
        private readonly IUserDataAccess _userDataAccess;
        private readonly IReportAccess _reportAccess;
        private readonly IAccountDataAccess _accountDataAccess;
        private readonly IRoleDataAccess _RoleDataAccess;
        public SuperAdminController()
        {
            this._userDataAccess = new UserDataAccess();
            this._reportAccess = new ReportAccess();
            this._accountDataAccess = new AccountDataAccess();
            this._RoleDataAccess = new RoleDataAccess();
        }       
        public ActionResult SADashboard()
        {
            return View();
        }

        public ActionResult TestPage()
        {
            ViewBag.PageTitle = "Users";
            ViewBag.TitleClass = "dripicons-user-group";
            List<UserModel> list = new List<UserModel>();
            list = _userDataAccess.GetUsers();
            return View(list);
        }

        public ActionResult SAECIUser()
        {
            ViewBag.PageTitle = "Users";
            ViewBag.TitleClass = "dripicons-user-group";
            List<UserModel> list = new List<UserModel>();
            list = _userDataAccess.GetUsers();
            return View(list);

        }

        public ActionResult SAECIAccounts()
        {
            ViewBag.PageTitle = "Accounts";
            ViewBag.TitleClass = "dripicons-Contact-group";
            List<AccountModel> list = new List<AccountModel>();
            list = _userDataAccess.GetCompanyListsAll().ToList();
            return View(list);

        }


        public ActionResult SAECIUserAdd()
        {
            UserModel userModel = new UserModel();
            return PartialView(userModel);
        }

        [HttpPost]
        public ActionResult SAECIUserAdd(UserModel userModel)
        {
            if (ModelState.IsValid)
            {
                userModel.UserType = 2;
                userModel.UserStatus = 0;
                userModel.Password = "12345";
               int Result  = _userDataAccess.AddECIUser(userModel);
            }
            return RedirectToAction("SAECIUser");
        }
        

        public ActionResult SAReport()
        {
            //int j = 0;
            //int i = 9;
            //float p = i / j;

            ViewBag.PageTitle = "Reports";
            ViewBag.TitleClass = "dripicons-graph-bar";          
            return View();
        }

        public JsonResult GetReport(int catname, int datalabel, int accountid, int yearid)
        {
            DataTable dt = _reportAccess.GetReports(catname, datalabel, accountid, yearid);

            List<Dictionary<string, object>> jsonlist = _reportAccess.GetTableRows(dt);

            return Json(jsonlist, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CheckReportName(int usernum, string reportname)
        {
            int result = _reportAccess.CheckReportName(usernum, reportname);
            return Json(result.ToString(), JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetNewDashboardReport(int catname, string[] datalabel, int accountid, string[] yearid, int compareaccount, string[] compareyear)
        {
            int accountid1 = compareaccount;
            string yearidprime = string.Join(",", yearid);
            string yearid1 = string.Join(",", compareyear);
            string datalabel1 = string.Join(",", datalabel);
            //if (accountyear != "0")
            //{
            //    string[] val = accountyear.Split('-');
            //    accountid1 = Convert.ToInt32(val[0].ToString());
            //    yearid1 = Convert.ToInt32(val[1].ToString());
            //}
            DataTable dt = _reportAccess.GetNewDashboardReport(catname, datalabel1, accountid, yearidprime, accountid1, yearid1);

            List<Dictionary<string, object>> jsonlist = _reportAccess.GetTableRows(dt);

            return Json(jsonlist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetNewDashboardReportOverall(int catname, int datalabel, int accountid, int yearid, int compareaccount, int compareyear)
        {
            int accountid1 = compareaccount;
            int yearid1 = compareyear;
            //if (accountyear != "0")
            //{
            //    string[] val = accountyear.Split('-');
            //    accountid1 = Convert.ToInt32(val[0].ToString());
            //    yearid1 = Convert.ToInt32(val[1].ToString());
            //}
            DataTable dt = _reportAccess.GetNewDashboardReportOverall(catname, datalabel, accountid, yearid, accountid1, yearid1);

            List<Dictionary<string, object>> jsonlist = _reportAccess.GetTableRows(dt);

            return Json(jsonlist, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetNewDashboardReportByFilters(int catname, string[] datalabel, int accountid, string[] yearid, string[] ddlindustry_arry, string[] ddlcmpysize_arry, string[] ddlrevenue_arry, string[] ddlagebrands_arry, string[] ddlgender_arry, string[] ddlrace_arry, string[] ddlgeoregion_arry, string[] ddlsupplier_arry, string[] ddlsupervisor_arry, string[] ddlunion_arry, string[] ddlpublicprivate_arry, string[] ddltenure_arry, string[] ddlsalaried_arry, string[] ddlmanageval_arry, string[] ddlmarketval_arry, int compareaccount, string[] compareyear)
        {
            int accountid1 = compareaccount;
            string yearidprime = string.Join(",", yearid);
            string yearid1 = string.Join(",", compareyear);
            string datalabel1 = string.Join(",", datalabel);
            //if (accountyear != "0")
            //{
            //    string[] val = accountyear.Split('-');
            //    accountid1 = Convert.ToInt32(val[0].ToString());
            //    yearid1 = Convert.ToInt32(val[1].ToString());
            //}
            //string ddlindustry_arry_result = string.Join(",", ddlindustry_arry);
            string ddlindustry_arry_result = string.Join(",", ddlindustry_arry);
            string ddlcmpysize_arry_result = string.Join(",", ddlcmpysize_arry);
            string ddlrevenue_arry_result = string.Join(",", ddlrevenue_arry);
            string ddlagebrands_arry_result = string.Join(",", ddlagebrands_arry);
            string ddlgender_arry_result = string.Join(",", ddlgender_arry);
            string ddlrace_arry_result = string.Join(",", ddlrace_arry);
            string ddlgeoregion_arry_result = string.Join(",", ddlgeoregion_arry);
            string ddlsupplier_arry_result = string.Join(",", ddlsupplier_arry);
            string ddlsupervisor_arry_result = string.Join(",", ddlsupervisor_arry);
            string ddlunion_arry_result = string.Join(",", ddlunion_arry);
            string ddlpublicprivate_arry_result = string.Join(",", ddlpublicprivate_arry);
            string ddltenure_arry_result = string.Join(",", ddltenure_arry);
            string ddlsalaried_arry_result = string.Join(",", ddlsalaried_arry);
            string ddlmanageval_arry_result = string.Join(",", ddlmanageval_arry);
            string ddlmarketval_arry_result = string.Join(",", ddlmarketval_arry);


            DataTable dt = _reportAccess.GetNewDashboardReportByFilter(catname, datalabel1, accountid, yearidprime, ddlindustry_arry_result, ddlcmpysize_arry_result, ddlrevenue_arry_result, ddlagebrands_arry_result, ddlgender_arry_result, ddlrace_arry_result, ddlgeoregion_arry_result, ddlsupplier_arry_result, ddlsupervisor_arry_result, ddlunion_arry_result, ddlpublicprivate_arry_result, ddltenure_arry_result, ddlsalaried_arry_result, ddlmanageval_arry_result, ddlmarketval_arry_result, accountid1, yearid1);

            List<Dictionary<string, object>> jsonlist = _reportAccess.GetTableRows(dt);

            return Json(jsonlist, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetNewDashboardOverallByFilter(int catname, int datalabel, int accountid, int yearid, string[] ddlindustry_arry, string[] ddlcmpysize_arry, string[] ddlrevenue_arry, string[] ddlagebrands_arry, string[] ddlgender_arry, string[] ddlrace_arry, string[] ddlgeoregion_arry, string[] ddlsupplier_arry, string[] ddlsupervisor_arry, string[] ddlunion_arry, string[] ddlpublicprivate_arry, string[] ddltenure_arry, string[] ddlsalaried_arry, string[] ddlmanageval_arry, string[] ddlmarketval_arry, int compareaccount, int compareyear)
        {
            int accountid1 = compareaccount;
            int yearid1 = compareyear;

            //if (accountyear != "0")
            //{
            //    string[] val = accountyear.Split('-');
            //    accountid1 = Convert.ToInt32(val[0].ToString());
            //    yearid1 = Convert.ToInt32(val[1].ToString());
            //}

           // string ddlindustry_arry_result = string.Join(",", ddlindustry_arry);
            string ddlindustry_arry_result = string.Join(",", ddlindustry_arry);
            string ddlcmpysize_arry_result = string.Join(",", ddlcmpysize_arry);
            string ddlrevenue_arry_result = string.Join(",", ddlrevenue_arry);
            string ddlagebrands_arry_result = string.Join(",", ddlagebrands_arry);
            string ddlgender_arry_result = string.Join(",", ddlgender_arry);
            string ddlrace_arry_result = string.Join(",", ddlrace_arry);
            string ddlgeoregion_arry_result = string.Join(",", ddlgeoregion_arry);
            string ddlsupplier_arry_result = string.Join(",", ddlsupplier_arry);

ECIAPP/Views/Home/CheckOTP-old.cshtml
@using ECIAPP.Models;
@model LoginVM
@{
    Layout = null;
}

<!DOCTYPE html>

   

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ECI | OTP</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="../bower_components/bootstrap/dist/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="../bower_components/font-awesome/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="../bower_components/Ionicons/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="../dist/css/AdminLTE.min.css">
    <!-- iCheck -->
    <link rel="stylesheet" href="../plugins/iCheck/square/blue.css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    
</head>
<body class="hold-transition login-page">
    <div class="login-box">
        <div class="login-logo">
            <a href="index2.html"><b>ECI</b>Dashboard</a>
        </div>
        <!-- /.login-logo -->
        <div class="login-box-body">
            <p class="login-box-msg">OTP Verification</p>

            @using (Html.BeginForm("CheckOTP", "Home", FormMethod.Post))            {
                
                <div class="form-group has-feedback">
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                    <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                </div>
                @Html.HiddenFor(x => x.Usernum)
                @Html.HiddenFor(x => x.otp)
                <div class="row">
                    
                    <!-- /.col -->
                    <div class="col-xs-4">
                        <input type="submit" class="btn btn-primary btn-block btn-flat" value="Verify" />

                    </div>
                    <!-- /.col -->
                </div>
                <br />
                <div class="row">
                    <div class="callout callout-danger">
                        @ViewBag.Message
                    </div>
                </div>
                
            }

            <div class="social-auth-links text-center" style="display:none">
                <p>- OR -</p>
                <a href="#" class="btn btn-block btn-social btn-facebook btn-flat">
                    <i class="fa fa-facebook"></i> Sign in using
                    Facebook
                </a>
                <a href="#" class="btn btn-block btn-social btn-google btn-flat">
                    <i class="fa fa-google-plus"></i> Sign in using
                    Google+
                </a>
            </div>
            
        </div>
        <!-- /.login-box-body -->
    </div>
    <!-- /.login-box -->
    
        <!-- jQuery 3 -->
        <script src="../bower_components/jquery/dist/jquery.min.js"></script>
        <!-- Bootstrap 3.3.7 -->
        <script src="../bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- iCheck -->
        <script src="../plugins/iCheck/icheck.min.js"></script>
    
    
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>

ECIAPP/Views/Home/CheckOTP.cshtml
@using ECIAPP.Models;
@model LoginVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>ECI | OTP Verification</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App Icons -->
    <link rel="shortcut icon" href="../blue/assets/images/favicon.ico">

    <!-- App css -->
    <link href="../blue/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/style.css" rel="stylesheet" type="text/css" />
    <script src="../blue/assets/js/jquery.min.js"></script>
    
</head>


<body>

    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <!-- Begin page -->
    <div class="accountbg"></div>
    <div class="wrapper-page">

        <div class="card">
            <div class="card-body">

                <h3 class="text-center m-0">
                    <a href="index.html" class="logo logo-admin"><img src="../blue/assets/images/ecilogo.png" height="50" alt="logo"></a>
                </h3>

                <div class="p-3">
                    <h4 class="text-muted font-18 m-b-5 text-center">Email Verification Code </h4>


                    @using (Html.BeginForm("CheckOTP", "Home", FormMethod.Post))
                    {

                        <div class="form-group has-feedback">
                            @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
                        </div>
                        @Html.HiddenFor(x => x.Usernum)
                        @Html.HiddenFor(x => x.otp)
                        <div class="form-group row m-t-20">

                            <div class="col-sm-12 text-center">
                                @*<button class="btn btn-primary w-md waves-effect waves-light" type="submit">Verify</button>*@
                                <button type="button" class="btn btn-primary waves-effect waves-light" id="sa-login">Verify</button>
                            </div>
                        </div>
                        <br />
                        <div class="row">
                            <div class="callout callout-danger">
                                @ViewBag.Message
                            </div>
                        </div>

                    }
                </div>

            </div>
        </div>

        <div class="m-t-40 text-center">
            @*<p>Don't have an account ? <a href="pages-register.html" class="font-500 font-14 text-primary font-secondary"> Signup Now </a> </p>
                <p>© 2018 Fonik. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>*@
        </div>

    </div>


    <!-- jQuery  -->

    <script src="../blue/assets/js/popper.min.js"></script>
    <script src="../blue/assets/js/bootstrap.min.js"></script>
    <script src="../blue/assets/js/modernizr.min.js"></script>
    <script src="../blue/assets/js/waves.js"></script>
    <script src="../blue/assets/js/jquery.slimscroll.js"></script>
    <script src="../blue/assets/js/jquery.nicescroll.js"></script>
    <script src="../blue/assets/js/jquery.scrollTo.min.js"></script>

    <!-- App js -->
    <script src="../blue/assets/js/app.js"></script>
    <script>
        //$(function () {
        //    $('input').iCheck({
        //        checkboxClass: 'icheckbox_square-blue',
        //        radioClass: 'iradio_square-blue',
        //        increaseArea: '20%' // optional
        //    });
        //});
    </script>
    <script type="text/javascript">
        $(document).ready(function () {

            $('#sa-login').click(function () {

                var Usernum = $('#Usernum').val();
                var otp = $('#otp').val();
                var typedotp = $('#Password').val();
                
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("CheckOTPJS", "Home")',
                    data: { Usernum: Usernum, enotp: otp, typedotp: typedotp },
                    async: true,
                    success: function (data) {
                        if (data.Message == "Success") {

                        sessionStorage.setItem("UserNum", data.UserNum);
                        sessionStorage.setItem("FName", data.FName);
                        sessionStorage.setItem("LName", data.LName);
                        sessionStorage.setItem("AccountId", data.AccountId);                        
                        sessionStorage.setItem("MenuList", data.MenuList);
                        sessionStorage.setItem("UserType", data.UserType);


                        var obj = JSON.parse(data.MenuList);
                        var matches = jQuery.grep(obj, function (item) {
                            return (item.ParentId === 0);
                        });

                        if (Object.keys(obj).length != 0) {
                            for (i = 0; i < Object.keys(obj).length; i++) {

                                if (obj[i].ParentId == 0) {
                                    if (obj[i].URLPath == "AlterDashboard") {
                                        LoadNewScreen("@Url.Action("AlterDashboard", "SuperAdmin")");
                                    return false;
                                }
                                else {
                                    if (i - matches.length == -1) {
                                        var url = '@Html.Raw(Url.Action("Menu", "SuperAdmin"))';
                                        var params = url.replace('Menu', obj[i].URLPath);
                                        LoadNewScreen(params);
                                        return false;
                                    }
                                }
                            }
                        }
                    }
                    else {
                        LoadNewScreen("@Url.Action("WIP", "SuperAdmin")");
                        return false;
                    }


                    }
                    else {
                        alert(data.Message);
                        return false;
                    }
                    }
                });

            });
        });
        function LoadNewScreen(url) {
            if (window.navigator.userAgent.indexOf("Edge") > -1) {
                location.href = url;
            }
            else {
                location.reload(); location.href = url;
            }
        }
    </script>
</body >
</html >

ECIAPP/Views/Home/ForgetPass.cshtml
@using ECIAPP.Models;
@model ForgetVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>ECI | Forget Password</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App Icons -->
    <link rel="shortcut icon" href="../blue/assets/images/favicon.ico">

    <!-- App css -->
    <link href="../blue/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/style.css" rel="stylesheet" type="text/css" />
    <script src="../blue/assets/js/jquery.min.js"></script>

</head>


<body>

    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <!-- Begin page -->
    <div class="accountbg"></div>
    <div class="wrapper-page">

        <div class="card">
            <div class="card-body">

                <h3 class="text-center m-0">
                    <a href="index.html" class="logo logo-admin"><img src="../blue/assets/images/ecilogo.png" height="50" alt="logo"></a>
                </h3>

                <div class="p-3">
                    <h4 class="text-muted font-18 m-b-5 text-center">Send Email Verification </h4>


                    @using (Html.BeginForm("ForgetPass", "Home", FormMethod.Post))
    {

                <div class="form-group has-feedback">
                    <label for="userpassword">Email-ID</label>
                    @Html.TextBoxFor(x => x.EmailId, new { @class = "form-control" })
                    @Html.ValidationMessage("EmailId", new { @class = "alert-danger" })
                </div>
                <div class="form-group row m-t-20">

                    <div class="col-sm-12 text-center">
                        <button class="btn btn-info mb-5 waves-effect waves-light" type="submit"><i class="mdi mdi-lock-open"></i>Send Link</button>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="callout callout-danger">
                        @ViewBag.Message
                    </div>
                   
                </div>
}
                </div>

            </div>
        </div>

        <div class="m-t-40 text-center">
            @*<p>Don't have an account ? <a href="pages-register.html" class="font-500 font-14 text-primary font-secondary"> Signup Now </a> </p>
                <p>© 2018 Fonik. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>*@
        </div>

    </div>


    <!-- jQuery  -->

    <script src="../blue/assets/js/popper.min.js"></script>
    <script src="../blue/assets/js/bootstrap.min.js"></script>
    <script src="../blue/assets/js/modernizr.min.js"></script>
    <script src="../blue/assets/js/waves.js"></script>
    <script src="../blue/assets/js/jquery.slimscroll.js"></script>
    <script src="../blue/assets/js/jquery.nicescroll.js"></script>
    <script src="../blue/assets/js/jquery.scrollTo.min.js"></script>

    <!-- App js -->
    <script src="../blue/assets/js/app.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
</body>
</html>

ECIAPP/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>
@Html.ActionLink("Login","Login")

ECIAPP/Views/Home/ResetPass.cshtml
@using ECIAPP.Models;
@model PasswordVM
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>ECI | Reset Password</title>
    <meta content="Admin Dashboard" name="description" />
    <meta content="Themesbrand" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App Icons -->
    <link rel="shortcut icon" href="../blue/assets/images/favicon.ico">

    <!-- App css -->
    <link href="../blue/assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/icons.css" rel="stylesheet" type="text/css" />
    <link href="../blue/assets/css/style.css" rel="stylesheet" type="text/css" />
    <script src="../blue/assets/js/jquery.min.js"></script>
    <script>
        $.getJSON("http://ipinfo.io", function (data) {
            // alert(data.ip);
            //$("#IpAddress").html("City: " + data.city + " ,County: " + data.country + " ,IP: " + data.ip + " ,Location: " + data.loc + " ,Organisation: " + data.org + " ,Postal Code: " + data.postal + " ,Region: " + data.region + "")
            $("#IpAddress").val(data.ip);
            console.log($("#IpAddress").val());
            //console.log($(window.navigator.userAgent));
           // $("#sysconfig").val(window.navigator.userAgent);

            //document.getElementById("IpAddress").value = data.ip;
            //console.log($("#IpAddress").val());
        })
    </script>
</head>


<body>

    <!-- Loader -->
    <div id="preloader"><div id="status"><div class="spinner"></div></div></div>

    <!-- Begin page -->
    <div class="accountbg"></div>
    <div class="wrapper-page">

        <div class="card">
            <div class="card-body">

                <h3 class="text-center m-0">
                    <a href="index.html" class="logo logo-admin"><img src="../blue/assets/images/ecilogo.png" height="50" alt="logo"></a>
                </h3>

                <div class="p-3">
                    @*<h4 class="text-muted font-18 m-b-5 text-center">Email Verification Code </h4>*@


                    @using (Html.BeginForm("ResetPass", "Home", FormMethod.Post))
    {

                <div class="form-group has-feedback">
                    <label for="userpassword">New Password</label>
                    @Html.PasswordFor(x => x.Password, new { @class = "form-control" })
                    @Html.ValidationMessage("Password", new { @class = "alert-danger" })
                </div>
                <div class="form-group has-feedback">
                    <label for="userpassword">Confirm New Password</label>
                    @Html.PasswordFor(x => x.ConfirmPassword, new { @class = "form-control" })
                    @Html.ValidationMessage("ConfirmPassword", new { @class = "alert-danger" })
                </div>
                @Html.HiddenFor(x => x.Usernum)
                @Html.HiddenFor(x => x.Status)
                <div class="form-group row m-t-20">

                    <div class="col-sm-6 text-right">
                        <button class="btn btn-info mb-5 waves-effect waves-light" type="submit"><i class="mdi mdi-lock-open"></i>Update</button>
                    </div>
                    <div class="col-sm-6 text-left">
                        @*<button class="btn btn-info mb-5 waves-effect waves-light" type="submit"><i class="mdi mdi-lock-open"></i>Cancel</button>*@
                        <button type="reset"  class="btn btn-info mb-5 waves-effect waves-light" onclick="userlogout();">Cancel</button>
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class="callout callout-danger">
                        @ViewBag.Message
                    </div>
                    <div style="display:none">
                        @Html.TextBoxFor(x => x.IpAddress)
                        
                    </div>
                </div>

}
                </div>

            </div>
        </div>

        <div class="m-t-40 text-center">
            @*<p>Don't have an account ? <a href="pages-register.html" class="font-500 font-14 text-primary font-secondary"> Signup Now </a> </p>
                <p>© 2018 Fonik. Crafted with <i class="mdi mdi-heart text-danger"></i> by Themesbrand</p>*@
        </div>

    </div>


    <!-- jQuery  -->

    <script src="../blue/assets/js/popper.min.js"></script>
    <script src="../blue/assets/js/bootstrap.min.js"></script>
    <script src="../blue/assets/js/modernizr.min.js"></script>
    <script src="../blue/assets/js/waves.js"></script>
    <script src="../blue/assets/js/jquery.slimscroll.js"></script>
    <script src="../blue/assets/js/jquery.nicescroll.js"></script>
    <script src="../blue/assets/js/jquery.scrollTo.min.js"></script>

    <!-- App js -->
    <script src="../blue/assets/js/app.js"></script>
    <script>
        $(function () {
            $('input').iCheck({
                checkboxClass: 'icheckbox_square-blue',
                radioClass: 'iradio_square-blue',
                increaseArea: '20%' // optional
            });
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {

          
            $('#backbutton').on('click', function (e) {
                alert('jesus');
            //e.preventDefault();
            LoadNewScreen("@Url.Action("Login", "Home/Login")");
            
        });

        });

       
        function userlogout() {
            var UserNum = sessionStorage.getItem("UserNum");

            $.ajax({
                type: 'POST',
                url: '@Url.Action("UserLogout", "SuperAdmin")',
                data: { Usernum: UserNum },
                async: true,
                success: function (data) {

                    var url = '@Html.Raw(Url.Action("Login", "Home/Login"))';
                        window.location.href = url;


                    }
            });
            //var i = sessionStorage.length;
            //while (i--) {
            //    var key = sessionStorage.key(i);
            //    if (/foo/.test(key)) {
            //        sessionStorage.removeItem(key);
            //    }
            //}
                }

</script>
</body>
</html>